name: Build GeyserHacks

on: push

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package -T 2C

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          files: target/geyserhacks-*.jar